emcmake cmake -S . -B dist/web ^
-DSDL3_DIR=%~dp0/libs/SDL-3.3.0-wasm/lib/cmake/SDL3 ^
-DSDL3_image_DIR=%~dp0/libs/SDL3_image-3.2.4-wasm/lib/cmake/SDL3_image ^
-DSDL3_mixer_DIR=%~dp0/libs/SDL3_mixer-3.1.0-wasm/lib/cmake/SDL3_mixer ^
-DSDL3_ttf_DIR=%~dp0/libs/SDL3_ttf-3.2.2-wasm/lib/cmake/SDL3_ttf ^
-DFREETYPE_INCLUDE_DIRS=%~dp0/libs/freetype-2.13.3-prefix/web/include ^
-DFREETYPE_LIBRARY=%~dp0/libs/freetype-2.13.3-prefix/web/lib/libfreetype.a ^
-DCMAKE_BUILD_TYPE=Debug ^
-DWITH_IMAGE=ON ^
-DWITH_MIXER=ON ^
-DWITH_TTF=ON
