name: Build

on: [push, pull_request]

jobs:
  desktop:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - { name: Linux,   os: ubuntu-latest }
          - { name: Windows, os: windows-latest }
          - { name: MacOS,   os: macos-latest }

    steps:
      - name: Set up SDL
        id: sdl
        uses: libsdl-org/setup-sdl@main
        with:
          version: sdl3-head
      - name: Get project sources
        uses: actions/checkout@v4
      - name: Build SDL
        uses: libsdl-org/setup-sdl@main
      - name: Configure (CMake)
        run: cmake -B build
      - name: Build (CMake)
        run: cmake --build build/

  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
      - name: Get project sources
        uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@master
      - name: Build SDL
        id: sdl
        uses: libsdl-org/setup-sdl@main
        with:
          version: sdl3-head
          cmake-toolchain-file: ${{ env.EMSDK }}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      - name: Configure (CMake)
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ env.EMSDK }}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_FIND_ROOT_PATH=${{ steps.sdl.outputs.prefix }}
      - name: Build (CMake)
        run: cmake --build build/

  android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - name: Get project sources
        uses: actions/checkout@v4
      - name: Download dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sdl_version=3.2.22
          sdl_mixer_version=3.2.4

          gh -R libsdl-org/SDL release download release-${sdl_version} -p 'SDL3-devel-*-android.zip'
          unzip "SDL3-devel-${sdl_version}-android.zip" -d app/libs SDL3-${sdl_version}.aar

          gh -R libsdl-org/SDL_image release download release-${sdl_mixer_version} -p 'SDL3_image-devel-*-android.zip'
          unzip "SDL3_image-devel-${sdl_mixer_version}-android.zip" -d app/libs SDL3_image-${sdl_mixer_version}.aar
      - name: Build gradle project
        run: |
          ./gradlew -i assembleRelease
